### ISSUE TITLE
strict-ssl warning appears when using download.strictSSL

### ISSUE THREAD

**Issue by jfacorro** [electron-userland/electron-packager#349] opened 2016-04-27 11:45 UTC
When building using `cli.js` I am always seeing the warning `The strict-ssl parameter is deprecated, use download.strictSSL instead`. I wanted to get rid of it so I checked [where and why](https://github.com/electron-userland/electron-packager/blob/529b6ddd93b39c75852751157f41cd358e5585f9/common.js#L146) it was generated. So it seems that in `common.js` we check if there is a `strict-ssl` option and warn if there is, but in `cli.js` we intentionally add that option with a default value.

I am probably missing something, but also this might be an inconsistency. I would be happy to open a PR if it is. 

> Which version of electron-packager are you using?

`7.0.0`

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

```
	electron-packager client application-name --platform=darwin \
		--arch=x64 --out=bin --icon=client/icon.icns \
		--ignore="node_modules/electron-*" \
		--overwrite
```

> What version of [Electron](http://electron.atom.io) are you building with?

`0.37.7`

> What is the host platform are you running electron-packager on?

`darwin`

> What target platform(s)/architecture(s) are you building for?

`darwin` & `win32`

> Is there a stack trace in the error message you're seeing?

No.

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Running `electron-packager` with the provided arguments shows the warning.

**Comment by malept** [comment] 2016-04-27 14:39
Thanks for filing an issue. The problem you describe has been fixed in version [7.0.1](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#701---2016-04-21), released on 2016-04-21.

**Comment by jfacorro** [comment] 2016-04-27 16:44
@malept Thank you for your quick response. I just updated `electron-packager` to version `7.0.1` but the warning is still there. I'm printing out the value of `args` in `cli.js` after arguments are processed by the `common.parseCLIArgs` function and this is what I get:

```
{ _: [ 'client', 'wall-monitor-kiosk' ],
  prune: false,
  asar: false,
  all: false,
  overwrite: true,
  download: { strictSSL: true },
  'strict-ssl': true,
  platform: 'win32',
  arch: 'x64',
  out: 'bin',
  icon: 'client/icon.icns',
  ignore: 'node_modules/electron-*',
  dir: 'client',
  name: 'wall-monitor-kiosk',
  protocols: [] }
``` 

As you can see the `strict-ssl` option is still there and so is the warning.

**Comment by malept** [comment] 2016-04-29 16:03
I can reproduce this.

**Comment by Bratkartoffl** [comment] 2016-05-13 14:40
I can reproduce this.

**Comment by malept** [comment] 2016-05-13 14:41
For any future commenters: yes, we know it's reproducible, we're just waiting on a fix now.

**Comment by seanmangar** [comment] 2016-05-18 10:12
Having the same issue, and the download seems to be very slow as well and even stalls.

**Closed** 2016-05-18 15:39 UTC
Labels: bug
