### ISSUE TITLE
Hangs extracting zip file on Windows 7

### ISSUE THREAD

**Issue by alepac** [electron-userland/electron-packager#1025] opened 2019-07-02 14:36 UTC
### Preflight Checklist

* [ x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * Electron Packager 14.0.0
  * Node v10.15.3
  * Host Operating system: win32 (x64)
* **Electron Version:**
  * v5.0.6
* **Operating System:**
  * Windows 7
* **Last Known Working Electron Packager version:**:
  * 

### Actual Behavior
The CLI hangs when extracting the electron zip file

### Additional Information
I try to remove the `C:\Users\pacificia\AppData\Local\electron` folder but with no success
* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. 
```
> set DEBUG=electron-packager && electron-packager . --out dist/

  electron-packager Electron Packager 14.0.0
  electron-packager Node v10.15.3
  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"_":["."],"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"out":"dist/","dir":".","protocols":[]} +3ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring application name from productName in C:\Users\pacificia\Documents\Workspace\ilapak-hmi-electron\package.json +0ms
  electron-packager Inferring appVersion from version in C:\Users\pacificia\Documents\Workspace\ilapak-hmi-electron\package.json +1ms
  electron-packager Inferring win32metadata.CompanyName from author in C:\Users\pacificia\Documents\Workspace\ilapak-hmi-electron\package.json +1ms
  electron-packager Inferring target Electron version from electron in C:\Users\pacificia\Documents\Workspace\ilapak-hmi-electron\package.json +4ms
  electron-packager Application name: ilapak-hmi +19ms
  electron-packager Target Electron version: 5.0.6 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"5.0.6","artifactName":"electron"} +0ms
Packaging app for platform win32 x64 using electron v5.0.6
  electron-packager Creating C:\Users\PACIFI~1\AppData\Local\Temp\electron-packager\win32-x64-template +12ms
  electron-packager Extracting C:\Users\pacificia\AppData\Local\electron\Cache\electron-v5.0.6-win32-x64.zip to C:\Users\PACIFI~1\AppData\Local\Temp\electron-packager\win32-x64-template +3ms
```

**Comment by malept** [comment] 2019-07-02 14:49
This is a duplicate of https://github.com/electron-userland/electron-packager/issues/1018

**Closed by malept** 2019-07-02 14:49 UTC
Labels: build-host:windows

**Comment by alepac** [comment] 2019-07-03 05:48
@malept I'm using the "Git Bash" not power shell, is it the same issue?

**Comment by malept** [comment] 2019-07-03 06:02
Yes. `cross-zip` invokes Powershell, it doesn't matter which shell you actually use.
