### ISSUE TITLE
Electron-packager not packaging

### ISSUE THREAD

**Issue by bartbouten** [electron-userland/electron-packager#565] opened 2017-01-25 14:32 UTC
I'm trying to create a package using the electron-packager. But it looks like it terminates itself after half a minute. 

This is what it looks like in the console:
```
C:\Users\Bart\Documents\Bart\Projecten\Angular 2\apex-diagnostic-tool>npm run package:win

> apex-diagnostic-tool@1.0.0 package:win C:\Users\Bart\Documents\Bart\Projecten\Angular 2\apex-diagnostic-tool
> electron-packager . APEXDiagnosticTool --ignore=src --ignore=e2e --ignore=.*\.conf\.js --ignore="(angular-cli|tsconfig)\.json" --ignore=webpack.*\.js --out=packages --
platform=win32 --arch=x64 --overwrite --asar

Packaging app for platform win32 x64 using electron v1.4.15

C:\Users\Bart\Documents\Bart\Projecten\Angular 2\apex-diagnostic-tool>
```

**Comment by englishextra** [comment] 2017-01-25 18:07
@bartbouten I guess that's because of multiple  --ignore

**Comment by malept** [comment] 2017-01-25 18:11
Thanks for reporting, this is a duplicate of #544. @bartbouten please run `SET DEBUG="*"`, re-run your electron-packager command, and please paste the output in that issue.

**Closed by malept** 2017-01-25 18:11 UTC
