### ISSUE TITLE
Node modules are not installed when using Yarn workspaces

### ISSUE THREAD

**Issue by martijnthe** [electron-userland/electron-packager#774] opened 2017-12-11 20:45 UTC
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

It seems like `electron-packager` doesn't play well with npm packages that have been hoisted to a node_modules parent folder. Is that by design? We're using yarn workspaces and npm packages get hoisted automatically to the root of the mono repo. Running electron "from source" works fine, because node's module resolution also looks in `node_modules` folder of parent folders.

Would you be interested in accepting a patch to solve this issue? Perhaps a new option key could be introduced for this?

Related issues:
- https://github.com/yarnpkg/yarn/issues/4070
- #527

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
$ electron-packager .
Packaging app for platform darwin x64 using electron v1.7.9
Wrote new app to [redacted]/electron-quick-start/packages/electron-app/electron-quick-start-darwin-x64
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager .
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

https://github.com/martijnthe/electron-quick-start/tree/repro-electron-packager-issue-774

To repro:
```
$ yarn -v  # make sure you've a recent version of yarn that supports workspaces
1.3.2
$ cd electron-quick-start
$ yarn
$ cd packages/electron-app
$ yarn electron . # Observe the app works fine when run "from source"!
$ yarn electron-packager .
yarn run v1.3.2
$ /Users/mthe/electron-quick-start/packages/electron-app/node_modules/.bin/electron-packager .
Packaging app for platform darwin x64 using electron v1.7.9
Wrote new app to /Users/mthe/electron-quick-start/packages/electron-app/electron-quick-start-darwin-x64
✨  Done in 2.32s.

# Now open the produced app. It will immediately throw an error
# that the "is-number" package cannot be found. This package is
# an npm dependency. Yarn automatically hoists this package to
# the root of the mono repo, but the packager doesn't traverse
# parent `node_modules` folders like node does.
```

**Comment by malept** [comment] 2017-12-11 21:19
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by martijnthe** [comment] 2017-12-12 09:48
@malept done!

**Comment by dancinglone** [comment] 2017-12-22 02:35
i came across with the same issue V_V

**Comment by malept** [comment] 2018-01-02 02:16
@martijnthe what sort of changes are you proposing?

**Comment by martijnthe** [comment] 2018-01-02 10:36
@malept that could work, will try. Thanks.

**Comment by brtthomp** [comment] 2018-01-15 21:18
I am having a similar issue but without yarn.

In my instance I am using stylus and pug (which are css and html pre-processors).   I use gulp to build each of these into a dist folder as well as copy the package.json file into the dist as well.  The reason I do this is because there are different builds that need to be done.  When I run `electron-packager` and point it to `dist` it will build without the `node_modules` folder thus causing problems.

My proposal would be that `electron-packager` looks up in parent directories to find a node_modules folder if one does not exist.  Otherwise I am force to either run `npm install` or copy the modules folder over on each build.

**Comment by malept** [comment] 2018-01-15 21:21
@brtthomp you have a different use case than the issue summary.

> Otherwise I am force to either run `npm install` or copy the modules folder over on each build.

Yes, those are your two options, given the current state of your build system.

**Comment by brtthomp** [comment] 2018-01-15 21:28
@malept 
I must have misunderstood the summary and read too much into the original title.  Sorry about that.

Thanks for the update.

**Comment by malept** [comment] 2018-01-26 17:39
I'm going to close this since I described a workaround in https://github.com/electron-userland/electron-packager/issues/774#issuecomment-354694049.

**Closed by malept** 2018-01-26 17:39 UTC
