### ISSUE TITLE
Linux - Invalid regular expression 

### ISSUE THREAD

**Issue by jonniespratley** [electron-userland/electron-packager#109] opened 2015-07-27 20:47 UTC
```
$ npm -v
2.10.1
$ node -v
v0.12.4
$ npm install
npm WARN package.json pg-explorer@0.0.3 No repository field.
npm WARN package.json Dependency 'json-proxy' exists in both dependencies and devDependencies, using 'json-proxy@^0.9.1' from dependencies
$ bower install
$ grunt build
[4mRunning "clean:dist" (clean) task[24m
[32m>> [39m1 path cleaned.

[4mRunning "processhtml:dist" (processhtml) task[24m

[4mRunning "ngtemplates:app" (ngtemplates) task[24m
File [36mapp/scripts/templates.js[39m created.

[4mRunning "less:development" (less) task[24m
File app/styles/pg-explorer.css created

[4mRunning "concat:distcss" (concat) task[24m
File dist/styles/bundle.css created.

[4mRunning "concat:dist" (concat) task[24m
File dist/scripts/bundle.js created.

[4mRunning "concat:modulesjs" (concat) task[24m
File dist/scripts/bundle-modules.js created.

[4mRunning "concat:modulescss" (concat) task[24m
File dist/styles/bundle-modules.css created.

[4mRunning "concat:styles" (concat) task[24m
File dist/styles/bundle-vendor.css created.

[4mRunning "concat:vendorjs" (concat) task[24m
File dist/scripts/bundle-vendor.js created.

[4mRunning "copy:semantic" (copy) task[24m
Created 4 directories, copied 7 files

[4mRunning "copy:bsfonts" (copy) task[24m
Created 1 directory, copied 5 files

[4mRunning "copy:fafonts" (copy) task[24m
Created 1 directory, copied 6 files

[4mRunning "copy:main" (copy) task[24m


[4mRunning "copy:pkg" (copy) task[24m
Copied 1 file

[4mRunning "requirejs:compile" (requirejs) task[24m
[32m>> [39mRequireJS optimizer finished
$ npm run-script build

> pg-explorer@0.0.3 build /opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop
> electron-packager . $npm_package_productName --prune --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager --ignore=.git

args { _: [ '.', 'pg-explorer' ],
  prune: true,
  asar: false,
  ignore: 
   [ 'node_modules/electron-prebuilt',
     'node_modules/electron-packager',
     '.git' ],
  dir: '.',
  name: 'pg-explorer',
  protocols: [] }
Using electron-prebuilt version 0.25.3 from /opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-prebuilt
/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/linux.js:69
        if (file.match(ignore[i])) {
                 ^
SyntaxError: Invalid regular expression: //opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/dist/: Nothing to repeat
    at new RegExp (native)
    at String.match (native)
    at userFilter (/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/linux.js:69:18)
    at startCopy (/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/node_modules/ncp/lib/ncp.js:43:14)
    at ncp (/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/node_modules/ncp/lib/ncp.js:32:3)
    at copyUserApp (/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/linux.js:32:7)
    at AppCreated (/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/linux.js:27:9)
    at cb (/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/node_modules/ncp/lib/ncp.js:255:37)
    at WriteStream.<anonymous> (/opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/node_modules/electron-packager/node_modules/ncp/lib/ncp.js:133:14)
    at WriteStream.g (events.js:199:16)

npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "build"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! pg-explorer@0.0.3 build: `electron-packager . $npm_package_productName --prune --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager --ignore=.git`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pg-explorer@0.0.3 build script 'electron-packager . $npm_package_productName --prune --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager --ignore=.git'.
npm ERR! This is most likely a problem with the pg-explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . $npm_package_productName --prune --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager --ignore=.git
npm ERR! You can get their info via:
npm ERR!     npm owner ls pg-explorer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/jenkins_build/workspace/Predix-Experience/Predix-Go++/pg-explorer-build-develop/npm-debug.log
```

**Comment by malept** [comment] 2015-09-18 05:19
I can't reproduce this on Linux. Which version of electron-packager are you using?

**Comment by malept** [comment] 2016-04-16 19:52
This is a pretty old bug without is not reproducible, so I'm closing it. If someone can reproduce it (with detailed steps so that others can also reproduce it), I would be happy to reopen.

**Closed by malept** 2016-04-16 19:52 UTC
Labels: bug, needs info
