### ISSUE TITLE
Allow packaging app using a locally-built electron

### ISSUE THREAD

**Issue by sltam** [electron-userland/electron-packager#500] opened 2016-09-28 22:08 UTC
Problem:
1. electron added a new sandbox feature in git.
2. I changed my app to take advantage of that feature.
3. Now I can't package an app for my customers to use until electron makes a release.

Therefore I hope I can package an app using electron-packager based on the copy of electron I built from git.

**Comment by malept** [comment] 2016-09-28 22:12
Thanks for filing an issue. This is a duplicate of a feature request filed in #187, so you should subscribe to that for updates. (It's mostly waiting for someone to write a pull request for the feature.) There are also workarounds described there.

**Closed by malept** 2016-09-28 22:12 UTC
Labels: duplicate
