### ISSUE TITLE
--asar-unpack  = "./node_modules/node-notifier/vendor/**" not working

### ISSUE THREAD

**Issue by MathijsvVelde** [electron-userland/electron-packager#189] opened 2015-11-09 16:08 UTC
whadup!!!

part of my package.json:
```package.json
  "devDependencies": {
    "coffee-script": "^1.10.0",
    "electron-rebuild": "^1.0.2"
  },
```

Executing on a Mac
```Shell
electron-packager	./app/ \
	"App Name" \
	--platform="darwin" \
	--arch="x64" \
	--version="0.34.3" \
	--out="dist/osx" \
	--icon="./assets/osx/icon.icns" \
	--app-bundle-id="com.app.name" \
	--app-version="0.0.1" \
	--ignore="node_modules/(electron-packager|electron-prebuilt)" \
	--prune \
	--asar \
	--asar-unpack="node_modules/node-notifier/vendor/" \

```

Even though I use the option 'prune' and the option 'ignore' on the node modules "electron-packager","electron-prebuilt", 'app.asar.unpacked' is NOT created

[@Asar reported issue ](https://github.com/atom/asar/issues/33)
[@node-notifier reported issue](https://github.com/mikaelbr/node-notifier/issues/76)

any idea's?

Thanks!!

**Comment by malept** [comment] 2015-11-09 16:11
Seems like you want `--asar-unpack-dir`, which is currently only in master.

**Comment by MathijsvVelde** [comment] 2015-11-09 16:21
I already tried that and it does not work either, sorry :disappointed:

**Comment by malept** [comment] 2015-11-10 01:57
Is it possible to create a minimal testcase app in a gist that reproduces the bug?

**Comment by MathijsvVelde** [comment] 2015-11-10 11:50
[like this](https://gist.github.com/MathijsvVelde/ba21081093500438b153)

**Comment by MathijsvVelde** [comment] 2015-11-11 12:08
any luck testing?

**Comment by MathijsvVelde** [comment] 2015-11-16 09:41
How is it going?
Can you give me a workaround in the meantime?

**Comment by malept** [comment] 2015-11-16 15:56
I haven't had a chance to try to reproduce it. I imagine the workaround is to just not use the asar feature, but I'm not particularly familiar with it.

**Comment by MathijsvVelde** [comment] 2015-11-16 16:19
Okay, I'm sorry to say this but, why the fuck did you bother to help me in the first place if you don't know a lot about asar?
Can you forward this issue to someone who's more familiar with asar?
Or can you tell me at least where to look, so I can try to fix it my self?
The least you can do is setting the asar dependency version to '0.8.3' (the latest), you'r currently using '0.6.1'...
There is a great chance that will help...

**Comment by sbruchmann** [comment] 2015-11-16 16:29
@MathijsvVelde Work on your attitude towards people who are trying to help you before working on code. It will come in handy in future conversations.

**Comment by malept** [comment] 2015-11-16 16:37
> why the fuck did you bother to help me in the first place if you don't know a lot about asar?

Because getting as much information about the issue (including how to reproduce is reliably) is important, especially if it turns out to be a bug. It will help anyone who decides to figure out what the problem is.

> Can you forward this issue to someone who's more familiar with asar?

The asar feature (like everything in electron-packager, really) is 100% community driven. If you can't wait for someone with an interest in this feature to take a look at this issue, perhaps try some other places in the [Electron community](https://github.com/atom/electron#community)?

> Or can you tell me at least where to look, so I can try to fix it my self?

This is quite literally how I would start: https://github.com/maxogden/electron-packager/search?l=javascript&q=asar&utf8=%E2%9C%93

> The least you can do is setting the asar dependency version to '0.8.3' (the latest), you'r currently using '0.6.1'...

I assumed you had the latest version of asar since you said you already tried `--asar-unpack-dir` per https://github.com/maxogden/electron-packager/issues/189#issuecomment-155112592. (The asar version change is here: https://github.com/maxogden/electron-packager/pull/174/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L20)

**Comment by MathijsvVelde** [comment] 2015-11-17 12:58
I apologize for my attitude, @sbruchmann and @malept!
It appears to be something wrong with your npm package...

on `npm un electron-packager; npm i electron-packager`
```shell
└─┬ electron-packager@5.1.1 
  ├─┬ asar@0.6.1 
  │ └── minimatch@2.0.4 
  ├─┬ plist@1.2.0 
  │ ├── base64-js@0.0.8 
  │ ├─┬ xmlbuilder@4.0.0 
  │ │ └── lodash@3.10.1 
  │ └── xmldom@0.1.19 
  ├── rcedit@0.3.0 
  └── run-series@1.1.4 
```
It is still using **asar@0.6.1** and the files aren't updated

it looks like NPM has not been updated yet.

**Comment by malept** [comment] 2015-11-17 16:55
As I [mentioned earlier](https://github.com/maxogden/electron-packager/issues/189#issuecomment-155109484), the `--unpack-asar-dir` feature has not been released on NPM yet. Are you able to reproduce your problem by [setting a git URL as the electron-packager source in your `package.json`](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)?

**Comment by malept** [comment] 2015-12-20 19:47
FYI, there is now a released version of electron-packager with `--unpack-asar-dir` (5.2.0).

**Comment by MathijsvVelde** [comment] 2015-12-21 14:31
:+1:

**Comment by malept** [comment] 2016-03-08 06:49
Since there hasn't been a response to whether `--unpack-asar-dir` solved the issue in some time, I'm closing it. If the problem still exists, please feel free to reopen.

**Closed by malept** 2016-03-08 06:49 UTC
Labels: feature:asar, needs info
