### ISSUE TITLE
React and electron-prebuilt-compile blank window

### ISSUE THREAD

**Issue by NathanBilleau** [electron-userland/electron-packager#707] opened 2017-08-19 21:40 UTC
I packaged an app (for windows) but when I run it, the window is blank ! I use React and electron-prebuilt-compile. I don't know how to fix that or what is the issue in my code. I tried with the electron quick start app and it worked so the issue comes from my project. 

The code is here : https://github.com/NathanBilleau/handi

Thank's

**Comment by malept** [comment] 2017-08-20 02:35
Thanks for filing an issue, but as it currently stands, the problem is much too vague. The reason could be any number of problems, several of them unrelated to Packager itself. I'm going to close this for now because the testcase you've provided is too complicated right now to debug. If you can condense the problem into a minimal testcase, then it will be easier for I or another developer to pinpoint what the issue is, and I will reopen this issue.

**Closed by malept** 2017-08-20 02:35 UTC
Labels: needs info

**Comment by NathanBilleau** [comment] 2017-08-21 19:04
I got news ! The packaged app seems not to be compiled (es6, babel...) so the code isn't readable in chromium, is there a specific thing to configure to fix that ?

**Comment by malept** [comment] 2017-08-21 19:43
Take a look at the docs for electron-compile.

**Comment by NathanBilleau** [comment] 2017-08-21 19:50
i already use ` electron-prebuilt-compile ` but it doesn't work

**Comment by malept** [comment] 2017-08-21 19:53
electron-compile is a direct dependency of electron-prebuilt-compile.

**Comment by yeahdongcn** [comment] 2018-01-16 08:53
I have the same issue here, it seems the js using react doesn't get compiled.
@NathanBilleau have you resolved this issue?
