### ISSUE TITLE
Symlinked packages (in monorepo) are not copied when when derefSymlinks is set to false

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-packager#757] opened 2017-11-17 02:26 UTC
* [X] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Hey all,

I am using a monorepo to manage my package and the monorepo is being created using lerna. Lerna symlinks my package together in the `node_modules`. So, to make sure they are included during the build, I have set `"deferSymlinks": false`. Here's the error I get:
```
An unhandled error has occurred inside Forge:
ENOENT: no such file or directory, stat '/private/var/folders/0t/xj_cwhvx45q8fxnwcd8mvg400000gn/T/electron-packager/darwin-x64/Universal React-darwin-x64/Electron.app/Contents/Re
sources/app/node_modules/@universal-react/components'
Error: ENOENT: no such file or directory, stat '/private/var/folders/0t/xj_cwhvx45q8fxnwcd8mvg400000gn/T/electron-packager/darwin-x64/Universal React-darwin-x64/Electron.app/Cont
ents/Resources/app/node_modules/@universal-react/components'
```
As you can see, my symlinked package is not being copied during the build process. Any idea how to fix this?

Thanks a bunch!

**Comment by malept** [comment] 2017-11-17 02:55
You misspelled `derefSymlinks`. Perhaps try that?

**Comment by walleXD** [comment] 2017-11-17 02:59
Ooops..... So, just tried to rebuild with `"derefSymlinks": false` but still get the same issue

**Comment by malept** [comment] 2017-11-17 03:02
I think this is a duplicate of #738 (which I need help with).

**Closed by malept** 2017-11-17 03:02 UTC
