### ISSUE TITLE
Upgrading to 7.0.1 causes Mac app to not start anymore

### ISSUE THREAD

**Issue by theflow** [electron-userland/electron-packager#350] opened 2016-04-27 12:49 UTC
I reproduced this with the electron-quick-start app (upgraded to electron 0.37.7):

1. Build a binary using 5.2.1
```
./node_modules/.bin/electron-packager . QuickStart4 --platform=darwin --arch=x64 --version=0.37.7
```
2. Double click the app in Finder -> works
3. Upgrade electron-packager to 7.0.1
4. Build binary again
```
./node_modules/.bin/electron-packager . QuickStart4 --platform=darwin --arch=x64 --version=0.37.7 --overwrite
```
5. Double click the app in Finder -> Alert opens with: The application “QuickStart4” can’t be opened.
6. This is in the Console:
```
Apr 27 14:40:49 Florians-MacBook-Pro-594 com.apple.xpc.launchd[1] (com.electron.quickstart4.463072[7579]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/flo/Projects/electron-quick-start/QuickStart4-darwin-x64/QuickStart4.app/Contents/MacOS/Electron
Apr 27 14:40:49 Florians-MacBook-Pro-594 com.apple.xpc.launchd[1] (com.electron.quickstart4.463072[7579]): Service setup event to handle failure and will not launch until it fires.
Apr 27 14:40:49 Florians-MacBook-Pro-594 Finder[415]: spawn_via_launchd() failed, errno=111 label=com.electron.quickstart4.463072 path=/Users/flo/Projects/electron-quick-start/QuickStart4-darwin-x64/QuickStart4.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #1136 LaunchApplicationViaLaunchDJobLabel() q=com.apple.root.default-qos
Apr 27 14:40:49 Florians-MacBook-Pro-594 Finder[415]: spawn_via_launchd() failed, errno=111 label=com.electron.quickstart4.463072 path=/Users/flo/Projects/electron-quick-start/QuickStart4-darwin-x64/QuickStart4.app/Contents/MacOS/Electron flags=1
```

Only tested on Mac OS X 10.11.4

Only way to fix that was to either reboot the machine or build the binary using a different name (different bundle-id didn't make a difference!)

**Comment by theflow** [comment] 2016-04-27 13:08
Moving the app bundle to a different folder and starting it from there also works, also after moving it back. This looks like an OS bug to me. Didn't find much when googling.

**Comment by malept** [comment] 2016-04-27 14:41
This sounds like a duplicate of https://github.com/electron-userland/electron-packager/issues/323.

**Comment by theflow** [comment] 2016-04-27 14:49
yeah, it is

**Comment by malept** [comment] 2016-04-27 14:50
I'm closing this as a duplicate, then.

**Closed by malept** 2016-04-27 14:50 UTC
Labels: duplicate

**Comment by theflow** [comment] 2016-04-28 08:21
might be worth putting a link to the issue in the release notes?

**Comment by malept** [comment] 2016-04-29 16:14
Added note to the 6.0.0 release notes.
