### ISSUE TITLE
Do not copy devDependencies into the packaged app, prior to the prune step

### ISSUE THREAD

**Issue by mhagmajer** [electron-userland/electron-packager#198] opened 2015-11-17 11:20 UTC
My dev dependencies are quite large (`babel` alone is over 300MB). The `electron-packager` analyses all those files which causes the build time to take a long time. I ended up explicitly ignoring all node modules that I want: 

```
--ignore='^/node_modules/(?!(invariant|mongodb))'
```

Why not make it the default behaviour of `electron-package` to ignore dev dependencies?

**Comment by malept** [comment] 2015-11-17 16:51
Thanks for the feature request, this is a duplicate of #35 (making `--prune` default).

**Comment by mhagmajer** [comment] 2015-11-17 19:14
@malept, I don't think these are duplicates. I commented on the other to make sure you see it.

**Comment by malept** [comment] 2015-11-17 19:24
*(I edited the issues so that the comment from #35 is here, as that's where it's relevant.)*

> I don't think these are the same issues. [...]

Fair enough. I can't think of a good reason to not ignore `devDependencies`. Feel free to create a PR to change the behavior. You may have some trouble now that NPM 3 has a flat `node_modules` folder.

**Comment by malept** [comment] 2016-02-28 19:08
See also: #235

**Comment by malept** [comment] 2016-10-30 18:29
I saw a really poor implementation of this the other day. I believe the correct way to do it is something like this (pseudocode):

```javascript
let package = require('./package.json');

// calculateDependencyTree returns a flat list of versioned dependencies, including
// sub-dependencies, for a given list of packages.
dependenciesToExclude() {
  let dependencies = calculateDependencyTree(package.dependencies);
  let devDependencies = calculateDependencyTree(package.devDependencies);
  return devDependencies - dependencies;
}
```

Ideally, this implementation does not depend on `npm` proper, because there have been at least two feature requests to be able to use alternative package managers.

**Comment by MarshallOfSound** [comment] 2017-08-15 07:26
This should be possible soon https://github.com/MarshallOfSound/pruner/pull/1

**Closed** 2018-03-31 14:46 UTC
Labels: enhancement, help wanted
