### ISSUE TITLE
Windows Vista-sized icons are not embedded into the exe correctly by rcedit

### ISSUE THREAD

**Issue by BrightLin** [electron-userland/electron-packager#912] opened 2018-11-28 10:38 UTC
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**### issue:   the app icon is dim and sawtooth**

Application icon：
![image](https://user-images.githubusercontent.com/15828392/49146091-5e457e00-f33c-11e8-8a11-2e6200644d51.png)

source ico file:
![image](https://user-images.githubusercontent.com/15828392/49146158-83d28780-f33c-11e8-97cb-189c5c99cebc.png)

**Comment by malept** [comment] 2018-11-28 17:00
I suspect that this is related to https://github.com/electron/rcedit/issues/79 (Electron Packager delegates Windows icon support to this program).

**Comment by allexzander** [comment] 2018-12-17 05:45
I am having the same issue after packaging the AppImage and running it on Ubuntu 18.04. For Ubuntu 16.04 it works just fine. Ubuntu 18.04 has this bad quality icon displayed. I tried different source files. Nothing works.

First screenshot is taken on Ubuntu 16.04
![sidebar_icon_16_04_](https://user-images.githubusercontent.com/12224014/50068642-45244480-01f9-11e9-877d-d4cf0d0968fc.png)

Second one - with bad quality - on Ubuntu 18.04
![sidebar_icon_18_04_bad_quality_](https://user-images.githubusercontent.com/12224014/50068674-6422d680-01f9-11e9-8864-7192a31b3d9e.png)

Source file:
![delete1](https://user-images.githubusercontent.com/12224014/50068727-959ba200-01f9-11e9-8718-a20334b037f5.png)

Steps to reproduce:

1. build an electron app with electron-builder.
2. package an AppImage with electron-packager.
3. run the app on Ubuntu 18.04

**Comment by malept** [comment] 2018-12-17 06:09
This issue is related to the Windows-specific problem. I don't really see why you need to use Electron Packager to build an AppImage. It would help if you provided more detailed repro steps.

**Comment by allexzander** [comment] 2018-12-17 06:11
@malept You are right. I probably need to create issue in `electron-builder` repo. Thx.

**Comment by malept** [comment] 2019-07-01 18:39
Since there's nothing that we can do in Electron Packager itself about this, I'm going to direct people to the rcedit bug I referenced earlier and close this bug.

**Closed by malept** 2019-07-01 18:39 UTC
Labels: blocked :no_entry_sign:, build-target:windows
