### ISSUE TITLE
Nothing happens when double-clicking Electron app

### ISSUE THREAD

**Issue by Overload119** [electron-userland/electron-packager#524] opened 2016-11-06 19:09 UTC
I have an app I'm working on:

https://github.com/Overload119/smilelapse

I run packager with the following command

`electron-packager . Smilelapse --overwrite`

It outputs the .app file but whenever I double-click the .app file nothing happens.
The app doesn't start.

Curiously, if I enter the app's package contents, and find the raw bin file, the app runs normally.

**Comment by malept** [comment] 2016-11-06 19:23
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`.

FWIW, I tried it on Linux x64 and aside from there not being an `app.dock` to hide, a file dialog opened for me.

**Comment by Overload119** [comment] 2016-11-06 20:32
Thanks for the quick response.

```
  electron-packager Electron Packager 8.2.0 +0ms
  electron-packager Node v5.7.0 +3ms
  electron-packager Host Operating system: darwin (x64) +2ms
  electron-packager Packager Options: {"_":[".","Smilelapse"],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":true,"prune":true,"dir":".","name":"Smilelapse","protocols":[]} +0ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring app-version from version in /Users/amirsharif/faceonion/package.json +13ms
  electron-packager Inferring target Electron version from electron in /Users/amirsharif/faceonion/package.json +5ms
  electron-packager Application name: Smilelapse +1ms
  electron-packager Target Electron version: 1.4.5 +0ms
  electron-packager Ignored path regular expressions: +0ms [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ]
  electron-packager Downloading Electron with options {"strictSSL":true,"platform":"darwin","arch":"x64","version":"1.4.5"} +14ms
Packaging app for platform darwin x64 using electron v1.4.5
  electron-packager Creating /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64-template +411ms
  electron-packager Extracting /Users/amirsharif/.electron/electron-v1.4.5-darwin-x64.zip to /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64-template +1ms
  electron-packager Initializing app in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64 from /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64-template template +2s
  electron-packager Ignored paths based on the out param: +4ms [ '/Users/amirsharif/faceonion/Smilelapse-darwin-ia32',
  '/Users/amirsharif/faceonion/Smilelapse-darwin-x64',
  '/Users/amirsharif/faceonion/Smilelapse-darwin-armv7l',
  '/Users/amirsharif/faceonion/Smilelapse-linux-ia32',
  '/Users/amirsharif/faceonion/Smilelapse-linux-x64',
  '/Users/amirsharif/faceonion/Smilelapse-linux-armv7l',
  '/Users/amirsharif/faceonion/Smilelapse-mas-ia32',
  '/Users/amirsharif/faceonion/Smilelapse-mas-x64',
  '/Users/amirsharif/faceonion/Smilelapse-mas-armv7l',
  '/Users/amirsharif/faceonion/Smilelapse-win32-ia32',
  '/Users/amirsharif/faceonion/Smilelapse-win32-x64',
  '/Users/amirsharif/faceonion/Smilelapse-win32-armv7l' ]
  electron-packager Running npm prune --production +7s
  electron-packager Renaming Electron to Smilelapse in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64/Electron.app/Contents/MacOS +7s
  electron-packager Renaming Electron Helper to Smilelapse Helper in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +2ms
  electron-packager Renaming Electron Helper.app to Smilelapse Helper.app in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64/Electron.app/Contents/Frameworks +1ms
  electron-packager Renaming Electron Helper EH to Smilelapse Helper EH in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper EH.app to Smilelapse Helper EH.app in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper NP to Smilelapse Helper NP in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper NP.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper NP.app to Smilelapse Helper NP.app in /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Moving /var/folders/2z/5_kcl_dx0qv1ky6b8g_j9x2r0000gn/T/electron-packager/darwin-x64/Smilelapse-darwin-x64 to /Users/amirsharif/faceonion/Smilelapse-darwin-x64 +1ms
Wrote new app to /Users/amirsharif/faceonion/Smilelapse-darwin-x64
```

Interestingly, I found that I get an error (although it has since gone away). 
I managed to get it to popup once on load, but the error seems to be with this line:
`tray = new Tray('./media/wink 20x20Template.png');`
It said something along the lines of failure to convert.

**Comment by malept** [comment] 2016-11-06 20:44
I think someone with a Mac is needed to debug this one, since I can't reproduce this behavior on Linux.

**Comment by inca** [comment] 2016-11-10 13:33
You'll get a reasonable output if you try and run the app in terminal, e.g.:

```bash
path/to/packaged.app/Contents/MacOS/App_name
```

In my case it's related to #241 which is, unfortunately, unanswered (I need to pass `-js-flags='--harmony_async_await'`).

**Comment by malept** [comment] 2017-02-19 03:04
No one's come forward to reproduce and debug this problem (I can't, I don't own a Mac), so I'm going to close it. I will be happy to reopen it if someone in the community wants to look into it.

**Closed by malept** 2017-02-19 03:04 UTC
Labels: build-target:mac, needs info, question
