### ISSUE TITLE
Pruning fails to remove platform specific optional packages

### ISSUE THREAD

**Issue by dgolovin** [electron-userland/electron-packager#821] opened 2018-04-06 18:42 UTC
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Starting from v12.0.0 I am getting 
``` shell
Failed to locate module "7zip-bin-linux" from "C:\p\rh\dpi\transpiled\node_modules\7zip-bin"

        This normally means that either you have deleted this package already somehow (check your ignore settings if using electron-packager).  Or your module installation failed.
```
when running on windows.

It seems the problem is in traversing development dependencies  when --prune option is used. 
--no-prune fixes the issue, but only for development builds. 

v11.2.0 works fine for both options.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager,flora-colossus`.**

```
   ... REMOVED ...
  electron-packager Downloading Electron with options {"strictSSL":true,"platform":"win32","arch":"x64","version":"1.8.4"} +0ms
Packaging app for platform win32 x64 using electron v1.8.4
  electron-packager Creating C:\Users\eskimo\AppData\Local\Temp\electron-packager\win32-x64-template +409ms
  electron-packager Extracting C:\Users\eskimo\.electron\electron-v1.8.4-win32-x64.zip to C:\Users\eskimo\AppData\Local\Temp\electron-packager\win32-x64-template +3ms
  electron-packager Initializing app in C:\Users\eskimo\AppData\Local\Temp\electron-packager\win32-x64\devsuite-win32-x64 from C:\Users\eskimo\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'C:\\p\\rh\\dpi\\dist\\win32-x64' ] +2s
... REMOVED ...
  flora-colossus walk reached: c:\p\rh\dpi\transpiled\node_modules\bluebird  Type is: DEV +0ms
  flora-colossus walk reached: c:\p\rh\dpi\transpiled\node_modules\builder-util  Type is: DEV +4ms
  flora-colossus walk reached: c:\p\rh\dpi\transpiled\node_modules\7zip-bin  Type is: DEV +1ms
Failed to locate module "7zip-bin-linux" from "c:\p\rh\dpi\transpiled\node_modules\7zip-bin"

        This normally means that either you have deleted this package already somehow (check your ignore settings if using electron-packager).  Or your module installation failed.
```

**Comment by malept** [comment] 2018-04-06 20:27
This should be fixed with https://github.com/MarshallOfSound/flora-colossus/pull/3

**Comment by malept** [comment] 2018-04-08 12:28
You can update the modules for Packager (specifically, `flora-colossus` and `galactus`) and this bug will be fixed.

**Closed by malept** 2018-04-08 12:28 UTC

**Comment by averissimo** [comment] 2018-10-02 16:54
I'm having the problem right now with 12.1.2 and `flora-colossus` v1.0.0` and galactus `v0.2.1`

*note*: `chai` is a dev-dependency

```
Error: Failed to locate module "chai" from "/home/averissimo/work/github/yakyak/app"

        This normally means that either you have deleted this package already somehow (check your ignore settings if using electron-packager).  Or your module installation failed.
    at Walker.<anonymous> (/home/averissimo/work/github/yakyak/node_modules/flora-colossus/lib/Walker.js:109:35)
    at step (/home/averissimo/work/github/yakyak/node_modules/flora-colossus/lib/Walker.js:32:23)
    at Object.next (/home/averissimo/work/github/yakyak/node_modules/flora-colossus/lib/Walker.js:13:53)
    at fulfilled (/home/averissimo/work/github/yakyak/node_modules/flora-colossus/lib/Walker.js:4:58)
```

**Comment by malept** [comment] 2018-10-02 17:22
@averissimo can you please create a minimal testcase and link it here?

**Comment by averissimo** [comment] 2018-10-02 17:33
I'm not sure how to setup a minimal testcase, below is a reproducible case:

yakyak/yakyak#Dodenis-upgrade-electron with electron-packager v12.* fails to build a package due to missing `chai` module (a dev depedency for tests).

Where using v11.* works without problems.

```
$ git clone https://github.com/yakyak/yakyak
$ cd yakyak
$ git checkout Dodenis-upgrade-electron
$ sed -i 's/"electron-packager": "^11.2.0"/"electron-packager": "^12.1.2"/g' package.json
$ npm install
$ DEBUG=electron-packager npm run deploy:linux
```

**Comment by malept** [comment] 2018-10-02 18:13
A minimal testcase would be starting with a fork of https://github.com/electron/electron-quick-start and then making the minimal number of changes necessary to reproduce the behavior you're seeing.

**Comment by malept** [comment] 2018-10-02 18:16
Also, this does not seem to be related to this particular bug (it's related to optional dependencies), when you do create a minimal testcase, can you please file a new bug and follow the issue template?
