### ISSUE TITLE
electron-db does not work when packaged

### ISSUE THREAD

**Issue by dipeshparashar** [electron-userland/electron-packager#981] opened 2019-04-18 14:50 UTC
### Preflight Checklist

* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 13.1.1
* **Electron Version:**
  * 4.1.4
* **Operating System:**
  *  win32 (x64)
* **Last Known Working Electron Packager version:**:
  * 

### Expected Behavior

After Packaging, the app should open as it does while development. Or the electron-packager should warn/throw error in case anything is not appropriate.

### Actual Behavior

The app packager successfully but gives an ENOENT error on opening it. 

### To Reproduce

I have tried a flat file structure (main, package, index all in parent folder). And also [recommended ](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working)file structure (src/main, index) . After the app is written is the specified folder.  On opening the Application file, an error is shown - ENOENT :  no such file or directory. open 'package.json'

### Additional Information

The details of all the package.json and cli are as follows -

![packJson](https://user-images.githubusercontent.com/8472277/56387935-4d41ce80-6243-11e9-970a-d16e9c084217.png)

And the detailed error is -

![App Error electron packager](https://user-images.githubusercontent.com/8472277/56369422-f0c8ba00-6216-11e9-9830-ca681d464957.png)

**Comment by malept** [comment] 2019-04-18 15:08
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by dipeshparashar** [comment] 2019-04-18 19:49
@malept , Thanks for the suggestion. Here is the basic project with all specified dependencies : [BasicProject](https://drive.google.com/uc?id=1OBzvinbj1KEE9fKzFtHYv5beb5qa33IC&export=download) , I  also tried adding asar explicitly based on the comments [here](https://github.com/electron-userland/electron-packager/issues/892) , but it did not help. I look forward to your review.

**Comment by malept** [comment] 2019-04-18 23:28
Unfortunately, what you provided is quite a bit more than a minimal Electron app. I work on this in my free time, and I can't allocate any time to debugging your app to figure out what's wrong with it.

I suspect what's happening is that [`electron-db` does not work when packaged](https://github.com/alexiusacademia/electron-db/issues/18).

Since this is not a bug with Electron Packager (but rather `electron-db`), I'm closing this issue.

**Closed by malept** 2019-04-18 23:28 UTC
Labels: invalid :x:

**Comment by dipeshparashar** [comment] 2019-04-19 14:02
@malept : I kept some bit in this version to test all dependencies which are called atleast once for a complete test. But yes, my bad on adding the node modules in the zip and i do respect your time. I was making a better minimal version again.  And while doing it, i did considered your suggestion on Electron-DB. And the good news is you are correct. The app is packaged and opened appropriately without it.

**The bug is indeed because of Electron-DB** .  

This debugging has taken many days and the project many weeks which started with electron-db as a core requirement. The only similar replacement to Electron-DB which i can find now is NeDB, but it seem to have [similar issues]([url](https://github.com/louischatriot/nedb/issues/587). 

Is there any suggestion for a simple DB for electron.

**Comment by malept** [comment] 2019-04-19 15:59
> Is there any suggestion for a simple DB for electron ?

I would suggest asking in one of the [community forums](https://electronjs.org/community). There aren't that many people watching this issue tracker.
