### ISSUE TITLE
packaging for OSX target duplicates Electron Framework.framework three times

### ISSUE THREAD

**Issue by iangcarroll** [electron-userland/electron-packager#345] opened 2016-04-24 21:24 UTC
In the built OS X binaries from electron-packager, three copies of `Electron Framework.framework` are essentially created. One in the root of `Contents/Frameworks/Electron Framework.framework`, one in `Contents/Frameworks/Electron Framework.framework/Versions/A`, and one in `Contents/Frameworks/Electron Framework.framework/Versions/Current`. The official Electron binaries use symlinks so that this does not happen.

> Which version of electron-packager are you using?

`^7.0.1`

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

`electron-packager . Uniscan --all --version=0.37.6 --overwrite --out=dist --asar`

> What version of [Electron](http://electron.atom.io) are you building with?

`^0.37.0`

> What is the host platform are you running electron-packager on?

Linux (Trusty on Travis)

> What target platform(s)/architecture(s) are you building for?

OS X

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Build an OS X application, go into `Contents/Frameworks/Electron Framework.framework` and observe the three duplicated copies of the framework.

**Comment by malept** [comment] 2016-04-24 21:38
I ran electron-packager 7.0.1 on Debian 8.4 and I cannot reproduce your results exactly. This is what I get:

```
Contents/Frameworks/Electron Framework.framework/Electron Framework -> Versions/Current/Electron Framework
Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
Contents/Frameworks/Electron Framework.framework/Versions/Current/Electron Framework
```

The first entry is a symlink (as denoted by the arrow). There would need to be some more investigation, but it looks like there's only two copies of the framework.

**Comment by iangcarroll** [comment] 2016-04-24 21:55
Ah, I was running `zip` without `--symlinks`, so that might be correct. I'll see what the build produces and let you know.

**Comment by malept** [comment] 2016-04-24 23:53
Hmm. Now I [wrote a testcase for this](https://github.com/electron-userland/electron-packager/commit/bd5c77ea355c49a25e628a7b7a725996770024e6) and I can't replicate any of it.

**Comment by iangcarroll** [comment] 2016-04-25 00:03
After zipping it [with `--symlinks`](https://github.com/iangcarroll/uniscan-electron/blob/master/.travis.yml#L16) it works properly for me. I'm not really sure what happened with your result. Should I leave this open for the two duplicates you encountered or can you no longer reproduce it?

**Comment by malept** [comment] 2016-04-25 00:04
I'm going to close it, since I wrote a testcase that does not fail.

**Closed by malept** 2016-04-25 00:04 UTC
Labels: build-target:mac, needs info
