### ISSUE TITLE
Error renaming file while packaging win32 x64 on OSX host using Electron v0.37.4

### ISSUE THREAD

**Issue by tleunen** [electron-userland/electron-packager#307] opened 2016-04-07 01:02 UTC
When running the packaging for all platform and all architectures, I'm hitting an error.

```
Packaging app for platform win32 x64 using electron v0.37.4
ENOENT: no such file or directory, rename '/var/folders/sd/nllql7z51k73kttbnbfz26q95ppffy/T/electron-packager/win32-x64/App-win32-x64/electron.exe' -> '/var/folders/sd/nllql7z51k73kttbnbfz26q95ppffy/T/electron-packager/win32-x64/App-win32-x64/App.exe'
```

> Which version of electron-packager are you using?

6.0.0

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

`electron-packager ./ --platform=all --arch=all --version=0.37.4 --asar=true --overwrite`

> What is the host platform are you running electron-packager on?

OSX

**Comment by malept** [comment] 2016-04-07 01:44
Oddly enough, Electron 0.37.4 made a bunch of backward-incompatible changes relative to electron-packager (and we hope to get a release out soon that is compatible with it, see the [6.0.1 milestone](https://github.com/electron-userland/electron-packager/milestones/6.0.1) for details). Does it work with Electron 0.37.3?

**Comment by malept** [comment] 2016-04-07 02:24
FWIW, I can't reproduce this with electron-packager 6.0.0, host platform linux, with the same command line.

**Comment by tleunen** [comment] 2016-04-07 03:10
No issues with 0.37.3

**Comment by malept** [comment] 2016-04-07 03:25
I assume the path in your error message is your temporary directory? When you run electron-packager to build with Electron 0.37.4 and it fails with the win32/x64 target, are there any `.exe` files in `/var/folders/sd/nllql7z51k73kttbnbfz26q95ppffy/T/electron-packager/win32-x64/App-win32-x64/`? If so, what are they?

**Comment by tleunen** [comment] 2016-04-07 03:31
The directory only has another directory called `resources` with `app.asar` inside.

**Comment by malept** [comment] 2016-04-07 06:30
I wonder if it has something to do with async + the order in which files are copied? (This is just a guess at this point.)

I don't have a Mac on which to debug this problem, can another community member look into this? At minimum, I'd like to know if someone else can reproduce the behavior (on OSX or otherwise).

**Comment by gliheng** [comment] 2016-04-07 08:25
I have a similar issue on Linux, albeit with a different version of electron.

> ~/Desktop/gf-trader-app$ electron-packager dist gf-trader --platform=linux --arch=x64 --out=release --icon=./builder/res/app.ico --version=0.35.1 --overwrite
> Packaging app for platform linux x64 using electron v0.35.1
> ENOENT: no such file or directory, rename '/tmp/electron-packager/linux-x64/gf-trader-linux-x64/electron' -> '/tmp/electron-packager/linux-x64/gf-trader-linux-x64/gf-trader'

**Comment by z-ax** [comment] 2016-04-07 11:26
I had once same problem, with 5.x, and it was resolved via re-downloading cache (with cleaning existing).
With Electron v0.37.4 at this point packager v6.0.0 only fails with the #300 for my build (on OS X host).

**Comment by tleunen** [comment] 2016-04-07 12:20
Thanks @z-ax, I cleaned up the cache and re-downloaded the electron for every platforms and now I'm able to build my app packages for all platforms.

Not sure what happened ine the first time during the download.

**Comment by z-ax** [comment] 2016-04-07 12:40
@tleunen, welcome.

I suppose it might be a cancelled command run (like Ctrl+C), or some other kind of error where it's halted and not cleaned. I'd suggest to `touch` some file inside cache after download to be sure it's finished, and re-download if it doesn't exist.

**Comment by tleunen** [comment] 2016-04-07 12:41
The zip file was there, but maybe corrupted.

**Comment by malept** [comment] 2016-04-07 15:32
My suggestion is for someone to file a bug in the [Electron project](https://github.com/electron/electron) to ask for checksums on their files when they generate releases.

See also: https://github.com/electron-userland/electron-prebuilt/issues/51

**Closed by malept** 2016-04-07 15:32 UTC
Labels: needs info

**Comment by mcmarinho** [comment] 2016-08-19 18:05
I had this problem too. In my case, proxy caused this fail.

**Comment by malept** [comment] 2016-08-19 18:25
See also: https://github.com/electron-userland/electron-download/issues/19
