### ISSUE TITLE
Fatal error: Unable to parse version string

### ISSUE THREAD

**Issue by simonroth** [electron-userland/electron-packager#400] opened 2016-06-16 11:33 UTC
`Fatal error: Unable to parse version string` when packaging app for platform win32 ia32 using electron v1.2.3 on Windows 8.1 Pro.

> Which version of electron-packager are you using?

7.0.4

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

`electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all`

> What version of [Electron](http://electron.atom.io) are you building with?

1.2.3

> What is the host platform are you running electron-packager on?

Windows 8.1 Pro x64

> What target platform(s)/architecture(s) are you building for?

`--all`

> Is there a stack trace in the error message you're seeing?

```
PS C:\Users\simon.roth\Downloads\electron-boilerplate-master\boilerplate> npm run build

> app@0.0.0 build C:\Users\simon.roth\Downloads\electron-boilerplate-master\boilerplate
> electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all

Packaging app for platform linux ia32 using electron v1.2.3
Packaging app for platform win32 ia32 using electron v1.2.3
Fatal error: Unable to parse version string
 undefined

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 build: `electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite
--all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.0 build script 'electron-packager . --out=dist --app-version=$npm_package_version --prune
 --asar --overwrite --all'.
npm ERR! This is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\simon.roth\Downloads\electron-boilerplate-master\boilerplate\npm-debug.log
```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Can be reproduced by building https://github.com/sindresorhus/electron-boilerplate.

**Comment by simonroth** [comment] 2016-06-16 14:59
Possibly related to https://github.com/npm/npm/issues/8574.

**Comment by malept** [comment] 2016-06-16 15:12
Try changing the `version` in `package.json` from `0.0.0` to `0.0.1`.

**Comment by adamweeks** [comment] 2016-06-17 02:31
I am getting the same error when building for win32 on a mac. 
`electron-packager build/ gifbar --platform=win32 --arch=x64 --overwrite --tmpdir=false --out=releases/ --app-version=0.0.2`
I do not get the error if I remove the `--app-version` param.

**Comment by malept** [comment] 2016-06-17 02:51
I can't reproduce either error.

* Host platform/arch: Linux x86_64
* Target platform/arch: Windows x64
* electron-packager version: 7.0.4
* Electron version: 1.2.3
* Wine version: 1.8.2 (32-bit)
* App versions tried: 0.0.0, 0.0.1, 0.0.2

This error also doesn't occur in our CI tests, which we have for all three platforms.

The error message comes from [`rcedit`](https://github.com/atom/rcedit/blob/e6d318d9d3754209b4930694b1f7e209ec4b3bed/src/main.cc#L64-L66). The definition of [the version string parser](https://github.com/atom/rcedit/blob/e6d318d9d3754209b4930694b1f7e209ec4b3bed/src/main.cc#L15-L27) indicates that it *should* work.

@simonroth does the error occur when you build for Windows x64? Are you sure `$npm_package_version` has a value in it?

@adamweeks Perhaps make sure that your version only contains ASCII? I'm at a loss as to what else to recommend trying here. (I'm assuming you're getting the exact same `Unable to parse version string` error.)

**Comment by simonroth** [comment] 2016-06-17 05:52
Good morning guys. It turned out that the error occures due to different variable substitution on Windows (see https://github.com/npm/npm/issues/8574 and http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/#thewindowsproblem). When changing

`$npm_package_version` to `%npm_package_version%`

the build passes without errors. It seems that it is not possible to run a build script using variable substitution cross plattform at the moment.

**Comment by malept** [comment] 2016-06-17 05:55
I'm closing this issue then, as the original problem has to do with NPM and not electron-packager.

**Closed by malept** 2016-06-17 05:55 UTC
Labels: build-target:windows, invalid

**Comment by simonroth** [comment] 2016-06-17 06:03
Okay, thanks.
