### ISSUE TITLE
Unable to find app. Don't know where to put package.json

### ISSUE THREAD

**Issue by CoderSudaWuda** [electron-userland/electron-packager#956] opened 2019-03-03 17:20 UTC
Whenever I run my app after compiling it with electron-packager, it returns the error: "Unable to find app." I know what the source is, it can't find package.json. I have package.json in my project folder, but for some reason, it doesn't get into the compiled folder. Where do I put my package.json?

Command I used: `electron-packager main.js REM the main file, when I run electron-packager ., it return s following error:`
![image](https://user-images.githubusercontent.com/38045884/53698763-2fadc800-3daf-11e9-81f0-480a13771a42.png)

Package.json:
```json
{
  "name": "text-editor",
  "version": "1.0.0",
  "description": "An application designed for typing (using images, words, etc.)",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "TheFatRat",
  "license": "ISC",
  "devDependencies": {
    "electron": "^4.0.6",
    "electron-packager": "^13.1.0"
  }
}
```

**Comment by malept** [comment] 2019-03-03 19:37
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by CoderSudaWuda** [comment] 2019-03-03 19:54
Can I just create a repo of my app and send the link to you?

**Comment by malept** [comment] 2019-03-03 20:20
I would prefer not, because I don't have time to debug a full Electron app. I work on this package in my spare time.

**Comment by CoderSudaWuda** [comment] 2019-03-03 20:27
There is only one window, with 4 files. Package.json, startingPoint.js, mainWindow.html, and scriptForHTML.js

**Comment by malept** [comment] 2019-03-03 20:29
Is it `package.json` or `Package.json`?

**Comment by CoderSudaWuda** [comment] 2019-03-03 20:54
package.json ; sorry I was using phone. I initialized it with `npm init`

**Comment by malept** [comment] 2019-03-03 21:01
> Command I used: electron-packager main.js REM the main file, when I run electron-packager ., it return s following error:

The error means that you did not run `npm install` after presumably adding it to `package.json` via a text editor. But you're not supposed to provide a JavaScript file to `electron-packager`, you're supposed to provide the folder where the `package.json` of your app is.

Unfortunately, due to the lack of additional information (namely, a minimal testcase with instructions to reliably reproduce the problem), I can't help any further. If you provide this information, I might be able to see what's wrong. I'm closing this issue until that happens.

**Comment by CoderSudaWuda** [comment] 2019-03-03 21:13
Ah ok, Ill do `electron-packager package.json`. If it doesnt work, Ill make a repo.

**Comment by malept** [comment] 2019-03-03 21:15
No, it's `electron-packager /path/to/folder`.

**Closed by malept** 2019-03-03 21:15 UTC
