### ISSUE TITLE
Web worker can not run after packaged again!!!

### ISSUE THREAD

**Issue by BruceAn1978** [electron-userland/electron-packager#859] opened 2018-06-11 01:36 UTC
The onmessage and postMessage function of web worker can interact well in vs code dev invironment, but the postMessage function can not response to the caller after packaged.

**html page**
var worker = new Worker('./js/uploader.js');
worker.onmessage = function(evt)
{
console.log('callback:' + evt);
};
worker.postMessage('hello');

**uploader.js**
onmessage = function(evt)
{
console.log(evt);
postMessage('world');
}

**package cmd:**
_electron-packager ./ FileUpload --platform=win32 --arch=ia32 --out ./target --app-version 3.0.0 --overwrite --icon=./app/img/file.ico --ignore=.history --ignore=.vscode --ignore=_recovery

**Comment by BruceAn1978** [comment] 2018-06-11 01:39
Don't close the issue carelessly!!!

I can reduce this problem by the code above: It works well in vs code dev environment, but no any response after packaged.

**Comment by BruceAn1978** [comment] 2018-06-11 01:40
So I don't think this is a problem of code is written.

**Comment by malept** [comment] 2018-06-11 03:58
Please do not file multiple issues for the same thing.

Duplicate of #858.

**Closed by malept** 2018-06-11 03:58 UTC
Labels: duplicate
