### ISSUE TITLE
Error building windows installer

### ISSUE THREAD

**Issue by paul321** [electron-userland/electron-packager#358] opened 2016-05-08 17:17 UTC
I'm trying to use the latest version with Electron 0.37.6, node 6.1.0, npm 3.8.6 but whatever i try it keeps give me this error:

Running "create-windows-installer:x64" (create-windows-installer) task
Warning: Cannot read property 'link' of undefined Use --force to continue.

I was trying it with Windows 7 which worked well until i updated to latest and OSX with wine

> Which version of electron-packager are you using?
Latest

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

> What version of [Electron](http://electron.atom.io) are you building with?

> What is the host platform are you running electron-packager on?

> What target platform(s)/architecture(s) are you building for?

> Is there a stack trace in the error message you're seeing?

> Please provide either a failing testcase or detailed steps to reproduce your problem.

**Comment by malept** [comment] 2016-05-08 17:43
Is `create-windows-installer` something you made or part of another module?

Is there a log file or debug output that you can enable?

**Comment by paul321** [comment] 2016-05-08 17:53
create-windows-installer it's the grunt task that wraps electron-packager unfortunately  there are no logs

**Comment by malept** [comment] 2016-05-08 17:54
Could you run the electron-packager command manually and paste the output?

**Comment by paul321** [comment] 2016-05-08 18:22
it seems the problem is from https://github.com/sindresorhus/grunt-electron
reverted from version 4.0.0 to 2.0.1

**Comment by malept** [comment] 2016-05-08 18:25
It sounds like this is not a bug in electron-packager, so I'm closing this issue.

**Closed by malept** 2016-05-08 18:25 UTC
Labels: invalid
