### ISSUE TITLE
Electron App not working correctly after packaging

### ISSUE THREAD

**Issue by Sahith27** [electron-userland/electron-packager#926] opened 2018-12-22 01:38 UTC
I created a project with electron named QMath. I added some python scripts to make my app works fast.
I finished up all the things. so I packaged it with 'electron-builder', that worked incorrectly.
I tried with 'electron-packager' that also didn't worked well.

I found that my node_modules folder is not packaged, then I added the modules in package.json file. but after that it doesn't work. I don't know why?

**Comment by malept** [comment] 2018-12-22 01:46
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* **Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem.** Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by malept** [comment] 2018-12-22 18:20
Without more information (specifically, a minimal testcase as I asked for in my previous comment), I cannot answer this question. I can only speculate as to what the problem could be. I can think of two things offhand:

* If your user does not have Python installed (as is the case for most Windows users), this app will not work. Installing Python itself is outside the scope of Electron Packager.
* Electron may not be able to find Python because it's not in the `PATH` environment variable when you open it via the file manager. This may be fixed by using the [`fix-path` module](https://www.npmjs.com/package/fix-path).

Since this question is not Electron Packager specific, you may have more luck at one of the [community forums](https://electronjs.org/docs/tutorial/support#finding-support).

**Closed by malept** 2018-12-22 18:20 UTC

**Comment by Sahith27** [comment] 2018-12-23 01:58
I tried in a windows pc without python installed. it doesn't run python in the app.
then I tried in my ubuntu pc with python installed. it doesn't run python too.

**Comment by Sahith27** [comment] 2018-12-23 16:36
Uncaught PythonShellError: python3: can't open file 'python/factor.py': [Errno 2] No such file or directory


    at PythonShell.parseError (/home/sahith/Documents/Programming/Math/Math-linux-x64/resources/app/node_modules/python-shell/index.js:240:21)
    at terminateIfNeeded (/home/sahith/Documents/Programming/Math/Math-linux-x64/resources/app/node_modules/python-shell/index.js:121:32)
    at ChildProcess.<anonymous> (/home/sahith/Documents/Programming/Math/Math-linux-x64/resources/app/node_modules/python-shell/index.js:113:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)

These lines have been logged in console when running after build

**Comment by malept** [comment] 2018-12-24 01:33
Please check out the [FAQ entry about relative paths](https://github.com/electron-userland/electron-packager/blob/v13.0.1/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working).

**Comment by Aurigano** [comment] 2019-12-27 10:22
I was having the same problem.
A temporary solution would be to copy and paste the python file and any other dependent file that your python file needs into the release-build/app/ folder.

I think electron packager couldn't pack python executables along with HTML, CSS and JS files.

But this exposes the actual code out of the package. In short, it's insecure.  
Please if anyone could help with that

**Comment by KSahithyan** [comment] 2019-12-27 12:15
@Aurigano Your solution may work. But if the user doesn't have python installed on his machine, this wouldn't work.
