### ISSUE TITLE
"Image not found" error when running Mac app on OS X built on linux

### ISSUE THREAD

**Issue by armaseg** [electron-userland/electron-packager#117] opened 2015-08-13 14:02 UTC
I've been trying to execute a program that I created using electron-packager on OS X and I get the following error:

<code>
dpyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: .........myApp.app/Contents/MacOs/./Electron
Reason: Image not found
</code>

I'm using electron-packager 5.0.1 on  Linux (Ubuntu) using this command:

<code>
electron-packager ./dist/ myApp --platform=all --arch=all --version=0.30.1 --asar --overwrite  --icon="./dist/src/resources/icon.png" --app-bundle-id="myApp"  --helper-bundle-id="myApp"
</code>

I tested the apps created on Win32 and Linux and they worked.  

Then, I downloaded electron-v0.30.1-darwin-x64.zip, extracted it and pasted the app.asar generated by electron-packager in the Electron's Resources folder and it worked.

**Comment by jasdeepkhalsa** [comment] 2015-11-02 11:46
I can also confirm this issue is happening with me when building for electron version 0.34.1 with electron-packager. Windows and Linux (both 32bit and 64bit) are working fine - only Mac64bit is having this issue.

**Comment by matthiasg** [comment] 2015-11-18 16:18
ok .. i currently dont have time to investigate any further, but the issue seems to be in the calls made to fs.symlink from somewhere inside the code. It tries to e.g link to inside the downloaded darwin electron release, but that the path is actually resolved incorrectly. e.g instead of downloading and unzipping electron-v0.35.0-darwin-x64.zip and then creating actual junction (or file/dir) symlinks what gets created are paths relative to the current working directory.

**Comment by bitwombat** [comment] 2015-11-23 22:42
This is happening with 5.1.1 as well.  Quite a show-stopper.  Can you suggest any workarounds for us to try until you have time to look at it?

**Comment by maxogden** [comment] 2015-11-23 23:05
It's difficult to reproduce this issue because of missing information requested here: https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md

The original issue is about building a Mac app on Linux with electron-packager 5.0.1 and electron 0.30.1. Every commenter after has been using different settings or hasn't included the necessary information to reproduce.

If someone can reliably reproduce this and wants to look into it, please do. If you are having this issue, leave as detailed as info as possible so that others can try to reproduce.

**Comment by bitwombat** [comment] 2015-11-25 00:01
I'm happy to try to create a testcase .  I think the hope by bug originators sometimes is that the error will be obvious to someone who knows the platform better than we do and we can avoid the hours it might take to create a reasonably simple testcase.

My info is very close to that posted above by jasdeepkhalsa 

Here it is in total.  Testcase to follow.

* Which version of electron-packager are you using?
5.1.1

* What cli arguments are you passing?
`electron-packager . UF --platform=darwin --arch=x64 --version=0.34.2 --overwrite`

* What platform are you running electron-packager on? 
Ubuntu 14.04.01 LTS (32-bit)

* What platform(s) are you building for?
OSX 10.10.5

* Is there a stack trace in the error message you're seeing?
No error on run of electron-packager.
Error when launching application on OSX: 
```
Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Desktop/*/UF.app/Contents/MacOS/Electron
  Reason: image not found
```

I should note there's also a bug filed with electron https://github.com/atom/atom/issues/9114 (probably because neither originator was sure where the bug lay).

**Comment by bitwombat** [comment] 2015-11-27 02:29
I'm petrified to report that OSX's connection to SMB shares is pathetically buggy.  I can't copy 2 GB folders from the share to my desktop without illogical errors.

And, I can't run electron apps that reside on shares.  If I move them locally, they're fine.  So, OSX bug.  Disappointing!

If I zip up the app, move it local to the mac, unzip it, and run it, I have a different problem:  https://github.com/maxogden/electron-packager/issues/205

**Comment by malept** [comment] 2016-10-30 17:45
Since there's no reproducible test case that doesn't involve remote shares (which is a filesystem-level bug, not an Electron Packager bug), I'm closing this. If someone can provide a minimal testcase as outlined in an earlier comment, I'll be happy to reopen.

**Closed by malept** 2016-10-30 17:45 UTC
Labels: bug, build-target:mac

**Comment by Jmales** [comment] 2017-01-12 16:50
I'm having the exact same problem, read the whole thread and can't figure out what's the solution. Anyone knows?

**Comment by eminoda** [comment] 2017-08-16 03:24
````
Process:               electron-quick-start [4512]
Path:                  /Volumes/VOLUME/*/electron-quick-start.app/Contents/MacOS/electron-quick-start
Identifier:            com.electron.electron-quick-start
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           electron-quick-start [4512]
User ID:               501

Date/Time:             2017-08-16 10:54:46.411 +0800
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        566A3EB1-5328-E549-E60C-1D5D75EDADFA
Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Volumes/VOLUME/*/electron-quick-start.app/Contents/MacOS/electron-quick-start
  Reason: no suitable image found.  Did find:
	/private/var/folders/q5/s2_05hcn0tz5j4bvdhbp0s9m0000gn/T/AppTranslocation/957472A0-9C27-4A39-9C19-99671AAD07CB/d/electron-quick-start.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short

````
"electron": "^1.7.5"

package on window10 64bit，cannot run on Mac（when use ‘electron-packager . --prune=true --overwrite --platform=darwin --arch=x64 --out=out --asar --icon=./favicon.ico’）

**Comment by malept** [comment] 2017-08-16 03:26
How did you copy the built Mac app from Windows to Mac?

**Comment by Almenon** [comment] 2017-10-29 01:23
I had this error when building on Windows and trying to open in mac.  Building on Mac fixed it.

https://github.com/electron-userland/electron-packager/issues/117
