### ISSUE TITLE
Errors when packaged with react, (Cannot find module 'read-pkg')

### ISSUE THREAD

**Issue by Dec-F** [electron-userland/electron-packager#822] opened 2018-04-09 11:08 UTC
The simplest packaged command I use does not have a packed react, but as long as the dependencies of react are installed, an error will occur. Errors when packaged with react, (Cannot find module 'read-pkg')

as follows

```js
//package.json 

{
  "name": "vkit",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "dotenv-expand": "4.2.0",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "raf": "3.4.0",
    "react": "^16.3.1",
    "react-dev-utils": "^5.0.1",
    "react-dom": "^16.3.1",
    "resolve": "1.6.0",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom",
    "ele": "electron main.js",
    "package": "electron-packager . app"
  },
  "devDependencies": {
    "electron": "^1.8.4",
    "electron-packager": "^12.0.0"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node",
      "mjs"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
```
The main.js, render.js, and index.html files are exactly the same as the electron-quick-start project.
When I run `npm run package` command, the error message is as follows
```bash
PS D:\Project\vkit> npm run package

> vkit@0.1.0 package D:\Project\vkit
> electron-packager . app

module.js:540
    throw err;
    ^

Error: Cannot find module 'read-pkg'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Project\vkit\node_modules\_read-pkg-up@2.0.0@read-pkg-up\index.js:3:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Project\vkit\node_modules\_get-package-info@1.0.0@get-package-info\lib\index.js:5:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vkit@0.1.0 package: `electron-packager . app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vkit@0.1.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

#### But when I remove all dependencies from `package.json`and reinstall the dependencies. it can be packaged again. I'm already dizzy, why the rely's dependencies interfere with electrons, and I'm not actually using react when I'm packing. Thank you

Thank you

**Comment by MarshallOfSound** [comment] 2018-04-09 11:10
Does this directory exist in your development environment?

> node_modules\_read-pkg-up@2.0.0@read-pkg-up

**Comment by Dec-F** [comment] 2018-04-09 11:18
@MarshallOfSound Yes, it exists

**Comment by malept** [comment] 2018-04-09 19:32
I can't reproduce this on Linux. What do you get when you run `npm list galactus`?

**Comment by Dec-F** [comment] 2018-04-10 01:27
@malept 
```bash
PS D:\Project\vkit> npm list galactus
vkit@0.1.0 D:\Project\vkit
`-- (empty)
```

Suddenly it was possible to run today. It may be that I restarted windows.

But now there is another problem. The packaging has been running, but it has not been completed. It took more than ten minutes.

```bash
PS D:\Project\vkit> npm run package

> vkit@0.1.0 package D:\Project\vkit
> electron-packager . app

Packaging app for platform win32 x64 using electron v1.8.4

```

**Comment by Dec-F** [comment] 2018-04-10 01:31
@malept @MarshallOfSound 
My project is at [GitHub](https://github.com/Dec-F/vkit)

**Comment by malept** [comment] 2018-04-10 01:59
In order to help you with your problem, we're going to need more information about it. In particular, the console output when you first execute `SET DEBUG=electron-packager`, and then execute `npm run package`.

**Comment by Dec-F** [comment] 2018-04-10 02:29
@malept I ran this command and nothing was output. However, after restarting windows, it can be packaged once. I hate windows, thank you very much for your help

**Comment by malept** [comment] 2018-04-10 02:35
There's nothing we can do to help if there's not more information given, so I'm going to go and close this issue.

**Closed by malept** 2018-04-10 02:35 UTC

**Comment by Dec-F** [comment] 2018-04-10 02:40
@malept Packaged again and running but not completed, I decided to develop on the virtual machine. I don't know what causes it, `node -v8.9.4`, `windows 10 1709`, running on the VM is fine.

**Comment by Shaya-pnc** [comment] 2018-07-14 13:46
Had the same issue when trying to run `vue ui`.
Solved by manually navigating to the relevant `node_modules` parent folder and running:
```
npm install read-pkg
```
Dunno why windows didn't install it in the first place, but after manually installing it - everything worked fine.
